package com.devtrack.infrastructure.persistence;

import com.devtrack.domain.ProjectStatus;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * JPA persistence model for a {@link com.devtrack.domain.Project}.
 * <p>
 * Deliberately kept separate from the domain entity: this class carries
 * persistence framework annotations, while {@code Project} stays a plain,
 * framework-free object. Mapping between the two happens in
 * {@link com.devtrack.infrastructure.persistence.mapper.ProjectPersistenceMapper}.
 * <p>
 * Getters/setters and constructors are generated by Lombok
 * ({@link Getter}, {@link Setter}, {@link NoArgsConstructor}, {@link AllArgsConstructor}).
 */
@Entity
@Table(name = "projects")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ProjectJpaEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private String description;

    @Enumerated(EnumType.STRING)
    private ProjectStatus status;
}
