package com.devtrack.infrastructure.persistence;

import com.devtrack.domain.TaskPriority;
import com.devtrack.domain.TaskStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * JPA persistence model for a {@link com.devtrack.domain.Task}.
 * <p>
 * The owning project is stored as a plain {@code project_id} column rather
 * than a JPA {@code @ManyToOne} relationship, mirroring the domain model's
 * decoupled aggregates and keeping persistence per-entity simple.
 * <p>
 * Getters/setters and constructors are generated by Lombok
 * ({@link Getter}, {@link Setter}, {@link NoArgsConstructor}, {@link AllArgsConstructor}).
 */
@Entity
@Table(name = "tasks")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class TaskJpaEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title;

    private String description;

    @Enumerated(EnumType.STRING)
    private TaskStatus status;

    @Enumerated(EnumType.STRING)
    private TaskPriority priority;

    @Column(name = "project_id", nullable = false)
    private Long projectId;
}
