package com.devtrack.infrastructure.persistence;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * JPA persistence model for a {@link com.devtrack.domain.TimeEntry}.
 * <p>
 * The owning task is stored as a plain {@code task_id} column rather than a
 * JPA {@code @ManyToOne} relationship, mirroring the domain model's
 * decoupled aggregates, consistent with {@link TaskJpaEntity}'s {@code project_id}.
 * <p>
 * Getters/setters and constructors are generated by Lombok
 * ({@link Getter}, {@link Setter}, {@link NoArgsConstructor}, {@link AllArgsConstructor}).
 */
@Entity
@Table(name = "time_entries")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class TimeEntryJpaEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "task_id", nullable = false)
    private Long taskId;

    // Named "entry_date", not "date": DATE is a reserved word in Postgres/H2/SQL Server
    // and would break DDL/queries if used verbatim as a column name.
    @Column(name = "entry_date", nullable = false)
    private LocalDate date;

    private BigDecimal hours;

    private String notes;
}
